# ────────────────────────────────────────────────────────────
# Custom Theme for Kitty
# Made with Omarchist
# ────────────────────────────────────────────────────────────

# Include theme from omarchy configuration
include ~/.config/omarchy/current/theme/kitty.conf

