-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Extra autostart processes

-- exec-once = uwsm-app -- my-service

-- Check lid state on startup/reload and disable laptop screen if closed

-- exec = ~/.config/hypr/lid-state-check.sh

--exec-once = sh -lc 'for pid in $(pgrep -x swaybg); do kill "$pid"; done; exec mpvpaper -o "loop panscan=1.0" "*" "$HOME/Downloads/lightning_front.mp4"'

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("kitty")
    -- hl.exec_cmd("hyprpaper")
    hl.exec_cmd("qs")
    hl.exec_cmd("udiskie")
    -- hl.exec_cmd("hyprmoncfgd")
    hl.exec_cmd("flatpak run net.sonuscape.mouseless")
end)
