[ids]
0001:0001:3c78431b
0001:0001:09b4e68d
4b45:3634:0b364cfd
4b45:3635:7701edbd
0001:0001:3c78431b

[global]
chord_timeout = 25

[main]
#capslock = layer(control)
capslock = timeout(layer(control), 175, layer(nav))
w+e = layer(nav)

a+s = layer(meta)
d+f = f3
i+o = layer(control)
s+d = layer(control)
u+i = layer(meta)

[nav]
h = left
k = up
l = right
j = down
